### ISSUE TITLE
Demo version

### ISSUE THREAD

**Issue by front-stream** [nikini/ionic-gallery-modal#1]
Could you add simple live demo version to this project? I can't use it because I see error: 
'view-controller.js:470 ModalCmp ionViewPreLoad error: No provider for ViewController!'

**Comment by nikini** [comment]
Hi @front-stream. I'll provide a demo for you, today.

**Comment by front-stream** [comment]
Thanks, I am waiting for it :) I am using ionic 2.0.0-rc.4

**Comment by nikini** [comment]
Check this out https://github.com/nikini/ionic-gallery-modal-demo
