### ISSUE TITLE
scroll on zoom?

### ISSUE THREAD

**Issue by phortonssf** [nikini/ionic-gallery-modal#10]
I installed the demo, how can I enable scroll on zoom? thank you

**Comment by phortonssf** [comment]
Actually zoom and scroll works wonderfully on ios but not on andriod. Any fixes for the scroll while zoomed on android? thank you. Looks great btw.

**Comment by MazinAffan-Kinesso** [comment]
@phortonssf this worked for me
```javascript
zoomable-image {

    ion-scroll {
        .image {
            touch-action: manipulation !important;
        }
    }
}
```

**Comment by phortonssf** [comment]
I put it in my app.scss and the page.scss. It sorta of works. When i try to
move while zoomed the image is basically cropped to that zoomed content.
Any ideas?

**Comment by MazinAffan-Kinesso** [comment]
not sure that I follow...after zooming I am able to move the image and view any part of it, the image isn't cropped

**Comment by phortonssf** [comment]
What file is your CSS in

**Comment by MazinAffan-Kinesso** [comment]
mine is only in app.scss

**Comment by phortonssf** [comment]
I'll try it again when I get home. But yeah when zoomed then tried to move
around the zoomed screen. It was treating the zoomed size as the max size
of the image. So no touch and scroll. Thanks .

**Comment by nikini** [comment]
Does it work now? can you try version 0.1.0?

**Comment by nikini** [comment]
Should be fixed in the new version, but I'm awaiting a response @phortonssf
