### ISSUE TITLE
Retrieve click coordinates

### ISSUE THREAD

**Issue by leonardoalt** [nikini/ionic-gallery-modal#13]
First of all, nice work!

Let's say I have a zoomed image, is it possible to retrieve the coordinates of a click on the image?

**Comment by nikini** [comment]
Thanks! I don't have the time right now to take care of it. I would want to promise that it's this week, but I cannot, since my time is very limited. I'll get some hours to work in it this week. I hope it'll be enough

**Comment by nikini** [comment]
You could retrieve the coordonates of the image by capturing the click event

**Comment by leonardoalt** [comment]
Alright, no problem.
Do you mean capturing the click event inside the code of ionic-gallery-modal, or on my code on a div or something like that wrapping the modal?

**Comment by nikini** [comment]
Well, you can always capture the click from the modal and get the event target (did not try it, myself, but should be possible)

**Comment by nikini** [comment]
I mean event target becauae you also have the close button in the moda

**Comment by nikini** [comment]
Did you capture them?
