### ISSUE TITLE
Build an android in production mode 

### ISSUE THREAD

**Issue by kristernavi** [nikini/ionic-gallery-modal#14]
this happen when i try to build it on production mode but when no --prod its working fine

> ionic-app-scripts build "--prod"

[01:58:20]  ionic-app-scripts 1.1.4
[01:58:20]  build prod started ...
[01:58:20]  clean started ...
[01:58:20]  clean finished in 6 ms
[01:58:20]  copy started ...
[01:58:20]  ngc started ...
[01:58:34]  build prod failed: Error encountered resolving symbol values statically. Calling function
            'makeParamDecorator', function calls are not supported. Consider replacing the function or lambda with a
            reference to an exported function, resolving symbol Injectable in
 c:/ionic_app/node_modules/ionic-gallery-modal/node_modules/@angular/core/src/di/metadata.d.ts,
            resolving symbol OpaqueToken in

**Comment by danielsogl** [comment]
I have the same problem

**Comment by LokeshInfoBeans** [comment]
I also have the same issues. Kindly suggest the solution for this.

**Comment by nikini** [comment]
Hello, as a suggestion maybe get the classes from here on github and use them directly in your project. I'll look into this when I have the time

**Comment by itskrsna** [comment]
Sorry @nikini  that didn't helped , Issue still occurs

**Comment by itskrsna** [comment]
@kristernavi  can you able to get a solution for the above issue ?
or 
any workaround?

**Comment by nikini** [comment]
Fixed in version 0.1.0
