### ISSUE TITLE
Swipe to close

### ISSUE THREAD

**Issue by tgezginis** [nikini/ionic-gallery-modal#15]
Thanks for your great job. I think swipe to close feature would be nice for native-like experience.

**Comment by nikini** [comment]
Yeah, I want to build that, but ionic-slides is a bit too limited for my tastes. That's the first todo on my list (after fixing some issues)

**Comment by nikini** [comment]
Should be in version 0.2.1 :)

**Comment by tgezginis** [comment]
👍
