### ISSUE TITLE
Error with Ahead of Time

### ISSUE THREAD

**Issue by martinop** [nikini/ionic-gallery-modal#2]
Hi, This is a nice lib for gallery but I have a problem when try to compile with AoT
the problem:

Unexpected value 'GalleryModal' declared by the module 'AppModule'

**Comment by nikini** [comment]
Can you show me you AppModule code? Seems like you haven't imported the GalleryModal

**Comment by krooshua** [comment]
Same issue when running production build

`ionic build --prod --release`

GalleryModal imported to AppModule and added to declarations and entryComponents

**Comment by nikini** [comment]
I have an updated version. Will be updating this soon. I think that may fix it

**Comment by nikini** [comment]
Can you check the new version?

**Comment by nikini** [comment]
The problem is a bit more complex. Ionic has removed a lot of functionalities. Back to the sketchboard. I'll be commiting a new version these days.

**Comment by nikini** [comment]
Fixed it for Ionic RC5 and fixed the other stuff. Can you please check now? v0.0.8

Otherwise, please provide a code example

**Comment by martinop** [comment]
Thanks, i will try

**Comment by marcelofb** [comment]
Hi, the error continues :(

**Comment by nikini** [comment]
I'm working on the bug. So far, as a workaround, if it's urgent, you can take the classes from the source of this repo and use them within your project

**Comment by shyamal890** [comment]
Hmm, facing the same issue, any updates?

**Comment by nikini** [comment]
No updates yet. Sorry, but I'm busy at work and this is outside my current work. I welcome any pull request and I approve it if it's ok :)

Will be on it this week, hopefully

**Comment by AmitMY** [comment]
Finally found something beautiful that my team agrees to use, and then this :(

**Comment by kctang** [comment]
@AmitMY If you need it now, just include the classes directly in your project. I tried it - very little effort and works nicely. You can switch back to depending on this package when this issue is resolved.

Even better if you can help fix it with a pr. It is free & open source after all. :-)

**Comment by AmitMY** [comment]
@kctang Works! Thanks.
If I'll figure the issue out, will definitely make a PR

**Comment by nikini** [comment]
The thing I want to test is the zoom functionality from the current slides component. If that should work properly, then this isn't needed anymore.

**Comment by nikini** [comment]
Can you test the new version (0.1.0) and tell me if you still have this issue?
