### ISSUE TITLE
Cannot read property 'nativeElement' of undefined

### ISSUE THREAD

**Issue by francoro** [nikini/ionic-gallery-modal#23]
this.scrollableElement = this.ionScrollContainer['_elementRef'].nativeElement.querySelector('.scroll-content');

is that line of code in zoomable-image.js
line 49

Please help

**Comment by nikini** [comment]
Fixed in version 0.1.0

**Comment by itskrsna** [comment]
After updating to 0.1.0 , im getting the same issue

**Comment by nikini** [comment]
Can you try 0.1.1? I've noticed someone else saying the same.

**Comment by itskrsna** [comment]
sure , let me check

**Comment by itskrsna** [comment]
it works with the Latest Version 0.1.1 and i can able to do prod build .
