### ISSUE TITLE
Error post update for ionic 3

### ISSUE THREAD

**Issue by GleidsonFerSanP** [nikini/ionic-gallery-modal#24]
Hi,
This error ocurred in my project post update for ionic 3
**Error: Error encountered resolving symbol values statically. Calling function 'makeParamDecorato r', function calls are not supported. Consider replacing the function or lambda with a reference to an export ed function, resolving symbol Injectable in**

Sorry for my weak english

**Comment by nikini** [comment]
Fixed in version 0.1.0
