### ISSUE TITLE
makeParamDecorator

### ISSUE THREAD

**Issue by zt-117** [nikini/ionic-gallery-modal#25]
ionic build android --prod --release :
build prod failed: Error encountered resolving symbol values statically. Calling function
'**makeParamDecorator**', function calls are not supported. Consider replacing the function or lambda with a
reference to an exported function, resolving symbol Injectable in
D:/ionic/node_modules/ionic-gallery-modal/node_modules/@angular/core/src/di/metadata.d.ts, resolving symbol
OpaqueToken in
D:/ionic/node_modules/ionic-gallery-modal/node_modules/@angular/core/src/di/opaque_token.d.ts, resolving
symbol OpaqueToken in
D:/ionic/node_modules/ionic-gallery-modal/node_modules/@angular/core/src/di/opaque_token.d.ts

**ionic2**

**Comment by nikini** [comment]
Fixed in version 0.1.0
