### ISSUE TITLE
 Cannot read property 'nativeElement' of undefined at ZoomableImage.ngOnInit 

### ISSUE THREAD

**Issue by nirajapril7** [nikini/ionic-gallery-modal#28]
Runtime Error
Uncaught (in promise): TypeError: Cannot read property 'nativeElement' of undefined TypeError: Cannot read property 'nativeElement' of undefined at ZoomableImage.ngOnInit

**Comment by nikini** [comment]
Hi @nirajkiul ! Did you try v0.1.1?

**Comment by nirajapril7** [comment]
Hi @nikini  
Ionic Framework: 3.2.1
Ionic App Scripts: 1.3.7
Angular Core: 4.1.0
Angular Compiler CLI: 4.1.0
Node: 6.9.5
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

**Comment by nikini** [comment]
Ok, but I mean the version of this library?

**Comment by nirajapril7** [comment]
@nikini! version- v0.0.9
"ionic-gallery-modal": "0.0.9"

**Comment by nikini** [comment]
Can you try v0.1.1 ?

**Comment by nirajapril7** [comment]
Yeah sure @nikini . I will try and let you know. Thanks :)

**Comment by davideas** [comment]
@nikini, could you please support version for ionic-angular@3.4.2 ?
We need this compatibility! Thanks.
