### ISSUE TITLE
When i use one image on array photos - Error

### ISSUE THREAD

**Issue by kkaabbaa** [nikini/ionic-gallery-modal#3]
EXCEPTION: Error in ./GalleryModal class GalleryModal - inline template:0:944 caused by: Cannot read property 'url' of undefined

I use like example

```
let modal = this.modalCtrl.create(GalleryModal, {
      photos: this.photos,
      initialSlide: 1
    });
    modal.present();
```

When use 2 or more all it fine

**Comment by krooshua** [comment]
Hi kkaabbaa,

Format is [{url: imageUrl}], try to update your code like this

`let modal = this.modalCtrl.create(GalleryModal, {
      photos: [{url: this.photos}],
      initialSlide: 1
    });
    modal.present();`

**Comment by kkaabbaa** [comment]
I realized what a mistake

I do not correctly passed index

initialSlide: 0 - when one image

Thx
