### ISSUE TITLE
Pinch zoom not working fine 

### ISSUE THREAD

**Issue by djsanj007** [nikini/ionic-gallery-modal#32]
Drag is restricted to 50% area of content after doing the Pinch zoom

**Comment by nikini** [comment]
Can you give me the versions of the package/ionic etc?

**Comment by bogomips** [comment]
I have the same issue with the last 0.2.2, pinch to zoom does not work fine.
1) it's very slow 
2) The the zoomed area does not correspond to the area I pinched on

    @ionic/cli-plugin-cordova       : 1.6.1
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.1.2 browser 4.1.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v8.2.1
    OS   : Linux 4.10
    npm  : 4.6.1
