### ISSUE TITLE
Update photos array when using the modal

### ISSUE THREAD

**Issue by pavel-kalmykov** [nikini/ionic-gallery-modal#35]
I'm currently using this module to view some pictures that are previously shown as thumbnails in a grid, and when I open the modal I pass an array of those low quality pictures to visualize them.

What I would like to do is to re-download the image that I am currently viewing in the modal to get the original quality one and exchange it (if not at real-time, at least before I open the modal).

I tried to do this by exchanging the initial image that I am about to open, but it only works with the first one, so when I swipe to the other ones, they still have the same quality as the thumbnails had. BTW, downloading all the images to its original size before passing them is not an option (it would consume a lot of Internet bandwidth).

So, is there any way to achieve this? If not, are you planning to implement the functionality described?

Thanks in advance.

**Comment by nikini** [comment]
So, you pass low quality images to the plugin and you want the plugin to redownload them when it opens? Then, it will redownload low quality images. It downloads the images you pass in the array.
