### ISSUE TITLE
Build --prod error

### ISSUE THREAD

**Issue by wesleymonaro** [nikini/ionic-gallery-modal#37]
Hi!

When I build my project with --prod, display the error:

[13:46:28]  build prod failed: Metadata version mismatch for module 
           project/node_modules/ionic-gallery-modal/ionic-gallery-modal.d.ts, found 
            version 3, expected 1 

[WARN] Error occurred during command execution from a CLI plugin (@ionic/cli-plugin-cordova).
Error: Metadata version mismatch for module /Users/roosevelt/Projetos/produtividadeApp/node_modules/ionic-gallery-modal/ionic-gallery-modal.d.ts, found version 3, expected 1

But, if the build is without --prod, it Works.

The command is ionic cordova build android --prod --release

I uninstalled the project gallery-modal and installed again, without success.

I downloaded the github project, I compiled it with the gulp, and the error remains.

In my package.json have "ionic-gallery-modal": "^0.2.1"

How can I resolve this?

Thank you!

**Comment by nikini** [comment]
Can you try 0.2.2 and let me know if that still shows you this error? Weird that you're getting that

**Comment by wesleymonaro** [comment]
@nikini It's solved! I updated to 0.2.2 version and the build was done! Thank you!

**Comment by abmnukmr** [comment]
Still getting same
