### ISSUE TITLE
Module makes click events fire 5 times

### ISSUE THREAD

**Issue by chdanielmueller** [nikini/ionic-gallery-modal#38]
Hi there,

Because of the usage of IonicModule.forRoot(...) in https://github.com/nikini/ionic-gallery-modal/blob/master/src/index.ts (click) events are executed 5 times on iOS devices.
Somehow multiple IonicModule.forRoot(...) render multiple views on top of each other which is no problem on Android devices or emulators.
Can you remove the usage of those?

Tested with ionic-angular 3.6.0

If I can help in any way please tell me.

Thanks,
Daniel

**Comment by nikini** [comment]
I can't remove the usage of those. Those give me access to the angular components so I can use them in my plugin. But I don't think it's coming from that.

What is you exact issue?

**Comment by chdanielmueller** [comment]
The problem is that the (click) action of button is being executed multiple times on iOS devices.
`<button (click)="clickAction()">`

Only on physical devices I was able to confirm this issue.
As soon as your module is no longer being imported this issue is resolved.
```
...
imports: [
    IonicModule.forRoot(MyApp),
    ...
    // ionicGalleryModal.GalleryModalModule
  ],
...
```

While searching for a solution for this problem I came across multiple posts which state that you should not use `IonicModule.forRoot()` more than once.

e.g.
- https://forum.ionicframework.com/t/ionic-2-click-event-firing-3-times-only-on-ios-devices/77464 (JakeWesorick's answer)
- https://github.com/ionic-team/ionic/issues/9610#issuecomment-274966270 (paulogr's answer on 24 Jan)

**Comment by muenzel** [comment]
I experience the exact same issue. An event is fired 5 times in my iOS simulator. In the web view instead, everything works fine.
This is for me a very severe problem b/c this causes 5 POST events send to my REST backend.

**Comment by chdanielmueller** [comment]
Hi @muenzel,

Could you please verify my solution?
If you don't want to check out the module, build it and edit the references in your own project you can replace the `node_modules/ionic-gallery-modal/index.js` with the content of the following file:
[index.js.txt](https://github.com/nikini/ionic-gallery-modal/files/1264426/index.js.txt)

Thanks,
Daniel

**Comment by muenzel** [comment]
@chdanielmueller thanks a lot for the quick fix! works like a charm

still need to add the new version to npm though

**Comment by chdanielmueller** [comment]
That's something @nikini needs to do.
Since this is only a bugfix which does not alter any functionality I would recommend to release as version 0.2.3.
