### ISSUE TITLE
To open the selected image in model unless specifying  'initialSlide'

### ISSUE THREAD

**Issue by akhilsanker** [nikini/ionic-gallery-modal#48]
Hi,
Using the plugin instead of ImageViewer plugin,due to advantage of navigation to other image by swiping.
But the modal is not opened with the selected image,every time either first or the specified index image is opened in slider.
Needs to open the clicked image in slider unless of the  'initialSlide' index.

Anybody has any suggestion.
Any  suggestion are appreciated.

Thanks,

**Comment by Flink91** [comment]
I do this:

`<img src="image.jpg" (click)="openGallery(1)">`

and in .ts

```
openGallery(initialSlide : number){

    let modal = this.modalCtrl.create(GalleryModal, {

      photos: photos,
      initialSlide: initialSlide

    });
    modal.present();
  }
```


I hope that's what you are looking for!
