### ISSUE TITLE
Is there anyway to use this for a single image?

### ISSUE THREAD

**Issue by gregavola** [nikini/ionic-gallery-modal#6]
We don't need the gallery features, just be able to use the single image to pop-up, sadly it doesn't work if we just important the `zoomable-image` component, any ideas?

**Comment by diegofal** [comment]
I have been able to use zoomable-image by itself. Which problems are you getting?

**Comment by nikini** [comment]
I'm also wondering why you could not use zoomable-image. But, anyway, I'll be looking into updating the plugin soon as well as supporting the final version of ionic 2

**Comment by nikini** [comment]
Should work with ionic 3 :)
