### ISSUE TITLE
Zoom going lower than min value

### ISSUE THREAD

**Issue by diegofal** [nikini/ionic-gallery-modal#7]
Lets say the image has its default size is 100x100

The zoom action is letting me go lower than that, and the image breaks when that happens.

Is this something you can restrict from the zoomable-image implementation? 
Thanks!

**Comment by diegofal** [comment]
Also, when the image is zoomed, scrolling through the image is not responding as expected. It flickers, like if the position.x or position.y is not being calculated correctly

**Comment by nikini** [comment]
I'll look at it. So, you tried an 100x100 image and the container is much larger, right?

**Comment by diegofal** [comment]
Well, I am not sure about the container itself.
 What I know is that I see the browser scrollbars in places I shouldnt, which means that there is a problem with the browser scrolling.

I am not being able to figure it out by debugging variables in the zoomable-image class. Perhaps you are luckier.

[UPDATE]

If I comment this line:

this.setScroll();

The flicker goes away.

Thanks!

**Comment by nikini** [comment]
Can you try the new version (0.1.0)?
