### ISSUE TITLE
got error when I add then to components array in app.module.ts

### ISSUE THREAD

**Issue by f0malin** [nikini/ionic-gallery-modal#9]
![image](https://cloud.githubusercontent.com/assets/680858/22771514/1a357b0e-eed2-11e6-8709-3ffa7b154e71.png)

it is the newest ionic 2 version

**Comment by nikini** [comment]
Can you try the new version (0.1.0)?

**Comment by nikini** [comment]
@formalin14 Waiting for a respons from you
